
    //get the left sidebar and right conent area elements //
const briyaniList = document.getElementById("briyani-list");
const recipeContent = document.getElementById("recipe-content");
//Define the recipes as an object //
const recipes = {
  'chicken-briyani' : {
    title : 'CHICKEN BRIYANI',
    ingredients: ['Basmati Rice : 2 Cups',
                   '1 lb boneless, skinless Chicken breast/thigh, cut into small pieces',
                   'Water  : 4 Cups',
                   'Oil : 2 tbsp or as per your need',
                   'Onion thinly sliced : 2',
                   'Garlic : 2 Cloves Minced',
                   'Grated Ginger : 1 tsp',
                   'Cumin seeds : 1 tsp',
                   'Bay leaf : 1',
                   'Star anise : 1',
                   'Black peppercorns : few',
                   'Cinnamon sticks : 1',
                   'Nutmeg(optional) : 1tsp (grounded)',
                   'Fennel Seeds : 1 tsp',
                   'Coriander Powder : 1 tsp',
                   'Garam Masala : 1 tsp',
                   'Turmeric Powder : 1 tsp',
                   'Red Chilli Powder : 1 tsp',
                   'Curd : As required',
                   'Salt : to taste',
                   'Lemon Juice : 2 tbsp',
                   'Fresh Cilantro, chopped',
                   'Mint leaves : Handful'
    ],
    instructions: ['Rinse rice; Soak for 30 min. Drain and set aside.',
                   'Heat Oil; Add bayleaf, star anise, cinnamon stick, black peppercorns and fennel seeds;Let it splutter ',
                   'Add onion, garlic, giner, cumin seeds and saute it till onion turns brown.',
                   'Add chicken; then add coriander powder, turmeric powder, red chillie powder and garam masala and saute it well.',
                   'Add curd to the chicken and spice mixture; Leave it for few mins. Add water if required',
                   'Add mint leaves and leave it for 15-18 mins or until the chicken is cooked through',
                   'In a seperate pot, boil water; add rice. Cook until 70% done.',
                   'Layer: rice, chicken mixture in a pot; seal with dough(Optional)',
                   'Cook on low heat for 10 - 15 minutes. ',
                   'Yumm !Your food is ready now !Serve hot with Raitha or brinjal curry'
    ]
    },
    'mutton-briyani' : {
      title: 'MUTTON BRIYANI',
      ingredients : ['Basmati Rice : 2 Cups',
        '1 lb mutton/lamb, cut into small pieces',
        'Water  : 4 Cups',
        'Oil : 2 tbsp or as per your need',
        'Onion thinly sliced : 2',
        'Garlic : 2 Cloves Minced',
        'Grated Ginger : 1 tsp',
        'Cumin seeds : 1 tsp',
        'Bay leaf : 1',
        'Star anise : 1',
        'Black peppercorns : few',
        'Cinnamon sticks : 1',
        'Nutmeg(optional) : 1tsp (grounded)',
        'Fennel Seeds : 1 tsp',
        'Coriander Powder : 1 tsp',
        'Garam Masala : 1 tsp',
        'Turmeric Powder : 1 tsp',
        'Red Chilli Powder : 1 tsp',
        'Curd : As required',
        'Salt : to taste',
        'Lemon Juice : 2 tbsp',
        'Fresh Cilantro, chopped',
        'Mint leaves : Handful'
],
      instructions :['Rinse rice; Soak for 30 min. Drain and set aside.',
        'Heat Oil; Add bayleaf, star anise, cinnamon stick, black peppercorns and fennel seeds;Let it splutter ',
        'Add onion, garlic, giner, cumin seeds and saute it till onion turns brown.',
        'Add mutton; then add coriander powder, turmeric powder, red chillie powder and garam masala and saute it well.',
        'Add curd to the chicken and spice mixture; Leave it for few mins. Add water if required',
        'Add mint leaves and leave it for 15-18 mins or until the chicken is cooked through',
        'In a seperate pot, boil water; add rice. Cook until 70% done.',
        'Layer rice, mutton mixture in a pot; seal with dough(Optional)',
        'Cook on low heat for 10 - 15 minutes. ',
        'Sprinkle some fried dried onions and tsp of Ghee(Optional).',
        'Yumm !Your food is ready now !Serve hot with Raitha or brinjal curry'
],
    },

    'Hyderabadi-chicken' : {
      title :'HYDERABADI CHICKEN BRIYANI',
      ingredients : ['For the chicken Marinade:',
                      'Chicken : 1kg(bone-in pieces preferred for more flavour)',
                      'Yogurt : 1 Cup',
                      'Ginger-garlic paste : 2 tablespoons',
                      'Red chilie powder : 2 teaspoons',
                      'Briyani masala : 2 tablespoons',
                      'Turmeric powder : 1 tsp',
                      'Lemon Juice : 2 tablespoons',
                      'salt : to taste',
                      'Fresh mint leaves : 1/4 cup, chopped',
                      'Fresh coriander leaves : 1/4 cup, chopped',
                      'Green chillies : 4-5, slit',
                      'Egg : 1 (optional, helps in binding the marinade)',
                      'FOR THE RICE',
                      'Basmati Rice : 500 gms',
                      'Water : as needed',
                      'Salt : to tase',
                      'Whole Spices',
                      'Bay Leaves : 2',
                      'Cinnamon Sticks : 2-inch piece',
                      'Cloves ; 4-5',
                      'Green cardamom pods : 4',
                      'Black peppercorns : 6-8',
                      'FOR LAYERING',
                      'Onions : 2 large, thinely sliced',
                      'Ghee : 4 tablespoons',
                      'Saffron : a pinch, soaked in 1/4 cup warm milk',
                      'Fried onions : 1/2 cup (optional, for garnish)',
                      'Fresh mint leaves : for layering'

      ],
      instructions : ['1. MARINATE THE CHICKEN:',

                        'In a large mixing bowl, combine yougurt, ginger-garlic paste, red chillie powder, turmeric powder, briyani masala, lemon juice, and salt',
                        'Add the chicken pieces to the marinade, ensuring they are well-coated.',
                        'Mix in the chopped mint, coriander leaves, slit green chillies, and the egg(if using).',
                        'Cover and refrigerate for at least 2 hours, preferably overnight for deeper flavour.',
                          '2. PREPARE THE RICE',
                          'Rinse the basmati rice under cold water until the water runs clear. Soak the rice in water for about 30 mins.',
                          'In a large pot, bring water to a boil. Add salt and the whole spices(bay leaves, cinnamon, cloves, cardamom, and perppercons.',
                          'Drain the soaked rice and add it to the boiling water.',
                          'Cook the rice until it;s 70% done(the grains should still have a slight bite.',
                          'Drain the rice and set aside.',
                          '3.FRY THE ONIONS',
                          'Heat 2 tablespoons of ghee in a large, heavy-bottomed pot or a Dutch oven.',
                          'Add the thinly sliced onions and sauté until they turn golden brown and caramelized.',
                          'Remove half of the fried onions for garnishing later.',
                          '4. COOK THE MARINATED CHICKEN',
                          'In the same pot with the remaining onions and ghee, add the marinated chicken.',
                          'Cook on medium heat, stirring occasionally, until the chicken is tender and the oil starts to separate from the gravy. This should take about 15-20 minutes.',
                            '5. LAYER THE BRIYANI',

                            'Once the chicken is cooked, evenly spread the partially cooked rice over the chicken layer.',
                            'Drizzle the saffron-infused milk over the rice.',
                            'Add the reserved fried onions on top.',
                            'Sprinkle fresh mint and coriander leaves.',
                              
                            'If using, add rose water and kewra water for extra fragrance.',

                            '6. DUM COOKING (STEAM COOKING)',
                            'Seal the Pot: Cover the pot with a tight-fitting lid. You can place a damp cloth or aluminum foil between the lid and the pot to trap the steam.',
                            'Cook on Low Heat: Place the sealed pot on a low flame. Let it cook for about 20-25 minutes. This allows the flavors to meld together and the rice to fully cook.',
                            'Alternatively, you can place the pot in a preheated oven at 180°C (350°F) for the same duration.',
                            '7.SERVING',
                            'Gently fluff the briyani before serving, mixing the layers slightly',
                            'Serve hot, garnished with the reserved fried onions. Accompany with Raita, salad or Mirchi ka Salna as per your references.',
                            'Enjoy your delicious homemade Hyderabadi Chicken Biryani!.'
   ] 

 
    },
    'Lucknowi-mutton' : {
      title : 'LUCKNOWI MUTTON BRIYANI',
      ingredients : ['FOR THE MUTTON MARINADE:',
                     'Mutton : 1 kg (bone-in pieces, preferably leg or shoulder).',
                     'Yougurt : 1 cup',
                     'Ginger-garlic paste : 2 tablespoons',
                     'Fried-onions : 1/2 cup (store-bought or homemade, cripsy and golden',
                     'Red chilie powder : 1 tsp',
                     'Turmeric Powder : 1/2 tsp',
                     'Garam Masala : 1 tsp',
                     'Green cardamom powder : 1/2 tsp',
                     'Coriander powder : 2 tsps',
                     'Lemon Juice :  2 tsp',
                     'Salt : to taste',
                     'Fresh mint leaves : 1/4 cup, chopped',
                     'Fresh coriander leaves : 1/4 cup, chopped',
                     'FOR THE RICE:',
                     'Basmati Rice : 500 grms (long grain)',
                     'Water : As needed',
                     'Salt : to taste',
                     'WHOLE SPICES',
                     'Bay leaves : 2',
                     'Cinnamon sticks : 1- inch piece',
                     'Cloves : 4-5',
                     'Green cardamon pods : 3-4',
                     'Black peppercorns : 6-8',
                     'Shahi Jeera(Caraway seeds) : 1/2 tsp',
                     'FOR THE BRIYANI',
                    'Ghee (Clarified Butter): 5 tablespoons',
                    'Saffron: A pinch, soaked in ¼ cup warm milk',
                    'Kewra Water: 1 tablespoon (optional)',
                    'Rose Water: 1 tablespoon (optional)',
                    'Fresh Mint Leaves: For layering',
                    'Fresh Coriander Leaves: For layering',
                    'Fried Onions: For garnish',
                    'Charcoal and Ghee: For the traditional "dum" smoking method (optional)',
      ],
      instructions: [ 'Prepation method :',
                    '1.MARINATE THE MUTTON:',
                    'In a large bowl, mix yogurt, ginger-garlic paste, fried onions, red-chillie powder, turmeric powder, garam masala, cardamom powder, coriander powder, lemon juice, salt, chopped mint, and coriander leaves',
                    'Add the mutton pieces and coat them well with the marinade.',
                    'Cover the bowl and let the mutton marinate in the refrigerator for at least 4 hours, preferably overnight for deeper flavours.',
                    '2. PREPARE THE RICE:',
                    'Rinse the basmati rice under cold water until the water runs clear. Soak the rice for 30 minutes.',
                    'In a large pot, bring water to boil, add salt and the whole spices (bay leaves, cinnamon, cloves, cardamom, peppercorns, and shahi jeera).',
                    'Add the soaked rice and cook until it is 70% done (al dente but firm).',
                    'Drain the rice and spread it on a tray to cool slightly.',
                    '3.COOK THE MUTTON:',
                    'Heat 3 tablespoons of ghee in a large heavy-bottomed pot or pressure cooker.',
                    'Add the marinated mutton and cook on medium heat for about 15-20 minutes until the mutton is half-cooked and oil separates.',
                    'Add 1 cup of water, cover, and simmer for another 20-25 minutes (or pressure cook for 3-4 whistles).',
                    'Once the mutton is tender and the gravy has thickened, turn off the heat.',
                    '4.LAYER THE BRIYANI:',
                    'In a large biryani pot, spread half of the cooked mutton with its gravy at the bottom.',
                          'Add a layer of the partially cooked rice on top.',
                          'Sprinkle fresh mint leaves, coriander leaves, and fried onions over the rice.',
                          'Drizzle with saffron milk, kewra water, and rose water.',
                          'Repeat with another layer of mutton, followed by a final layer of rice, and garnish similarly.',
                          '5. DUM COOKING (Steam Cooking):',
                          'Seal the Pot: Cover the pot with a tight-fitting lid. To create a steam-tight seal, place a damp cloth or aluminum foil between the lid and the pot.',
                          'Slow Cook: Place the sealed pot on a low flame (or on a heated tawa/griddle) for about 20-25 minutes to allow the biryani to cook in its own steam.',
                          'Alternatively, you can place the sealed pot in a preheated oven at 160°C (320°F) for 30 minutes.',
                          '6. OPTIONAL CHARCOL SMOKING (Dum Pukht Method):',
                          'Heat a piece of charcoal until red hot.',
                          'Place the hot charcoal in a small bowl, and carefully place this bowl in the center of the biryani pot.',
                          'Drizzle some ghee over the charcoal and immediately cover the pot to trap the smoky flavor. Let it sit for 5-10 minutes.',
                          '7. SERVING:',
                          'Once done, gently fluff the biryani layers.',
                          'Serve hot, garnished with fried onions, accompanied by Raita or Salan (spicy curry).',


                                          
                                    
      ]

    },
    'fish-briyani' : {
      title : 'FISH-BRIYANI',
      ingredients : ['FOR MARINATING THE FISH',
                     '500G fish fillets(preferably seer fish, kingfish, or any firm fish)',
                     'Turmeric Powder : 1 tsp',
                     'Red chillie powder : 1 tsp',
                     'Coriander Powder : 1 tsp',
                     'Garam Masala : 1 tsp',
                     'Ginger-garlic paste : 1 tbsp',
                     'Lemon juice : 1 tbsp',
                     'Salt to taste',
                     'FOR RICE :',
                     '2 cups basmati rice',
                     'Water : 4 cups',
                     'Cloves : 2-3',
                     'Cinnamon stick : 1-inch',
                     'Green Cardamom : 2-3',
                     'Bay leaf : 1',
                     'Salt to taste',
                     'FOR BRIYANI',
                     'Large onions, thinly sliced : 2',
                     'Tomatoes : 2 chopped',
                     'Green chillies : 2-3,slit',
                     'Red chillie powder : 1 tsp',
                     'Garam Masala : 1 tsp',
                     'Briyani masala : 1 tsp',
                     'Fresh mint leaves : 1/2 cup, chopped',
                     'Coriander leaves : 1/2 cup, chopped',
                     'Ghee : 2 tbsp',
                     'Oil : 3 tbsp',
                     'A few saffron strands soaked in 2 tbsp warm milk (or yellow food coloring)',
                      'Fried onions and boiled eggs (for garnish)',


      ],

       instructions: [
        'MARINATE THE FISH:',
       'Mix turmeric, red chili powder, coriander powder, garam masala, ginger-garlic paste, lemon juice, and salt in a bowl.',
        'Coat the fish fillets evenly with this mixture and let it marinate for at least 30 minutes.',
        'COOK THE RICE:',
        'Rinse the basmati rice under running water until the water runs clear. Soak the rice for 30 minutes, then drain.',
        'Boil 4 cups of water with cloves, cinnamon, cardamom, bay leaf, and salt. Add the soaked rice.',
        'Cook the rice until it is 80% done (slightly undercooked). Drain the water and set the rice aside.',
        'COOK THE FISH:',
        'Heat oil in a pan and shallow fry the marinated fish fillets until golden on both sides. Remove and set aside.',
        'Prepare the Biryani Base:',
        'In the same pan, add the ghee. Fry the sliced onions until golden brown and crispy. Set aside a portion for garnish.',
        'In the remaining oil, add green chilies, and tomatoes. Cook until the tomatoes turn soft.',
        'Add red chili powder, garam masala, biryani masala, and salt. Stir well to combine. Add little water if required',
        'Toss in the chopped mint and coriander leaves. Cook until the oil separates from the masala.',
        'LAYER THE BRIYANI:',
        'In a heavy-bottomed pot or biryani dish, spread half of the cooked rice.',
        'Layer with the fish fillets and spread the prepared masala over the fish.',
        'Top with the remaining rice.',
        'Drizzle saffron milk over the top and add some fried onions.',
        'Cover with a tight lid or seal with dough to ensure steam cooking (dum).',
        'DUM COOKING:',
        'Place the pot on a low flame or in a preheated oven at 180°C for 20-25 minutes to allow the flavors to meld.',
        'SERVE:',
        'Garnish with fried onions, boiled eggs, and fresh coriander. Serve hot with raita or salad on the side.',
        
        'Enjoy your fish biryani!'
       ],
    },
    'prawn-briyani' : {
      title : 'PRAWN BRIYANI',
      ingredients : ['FOR MARINATING THE PRAWNS:',
                    'Prawns : 500G cleaned and deveined',
                    'Turmeric powder : 1 tsp',
                    'Red chili powder :  1 tsp',
                    'Coriander powder : 1 tsp',
                    'Garam masala : 1 tsp',
                    'Ginger-garlic paste : 1 tbsp',
                    'Lemon juice : 1 tbsp',
                    'Salt to taste',
                    'FOR RICE',
                   'Basmati rice : 2 cups',
                   'Water : 4 cups',
                   'Cloves : 2-3',
                   'Cinnamon stick : 1 -inch',
                   'Bay leaf : 1',
                   'Salt to taste',
                   'For Biryani:',
                    '2 large onions, thinly sliced',
                    '2 tomatoes, chopped',
                    '2-3 green chilies, slit',
                    '1 cup yogurt (curd)',
                    '1 tsp red chili powder',
                    '1 tsp garam masala',
                    '1 tsp biryani masala (optional)',
                    '½ cup fresh mint leaves, chopped',
                    '½ cup fresh coriander leaves, chopped',
                    '2 tbsp ghee (clarified butter)',
                    '3 tbsp vegetable oil',
                    'A few saffron strands soaked in 2 tbsp warm milk (or yellow food coloring)',
                    'Fried onions and boiled eggs (for garnish)',
                  
                  ],
       instructions : [ 'MARINATE THE PRAWNS:',
                        'In a bowl, combine turmeric, red chili powder, coriander powder, garam masala, ginger-garlic paste, lemon juice, and salt.',
                        'Add the prawns and coat them thoroughly with the marinade.',
                        'Let it marinate for at least 30 minutes in the refrigerator.',
                        'COOK THE RICE :',
                        'Rinse the basmati rice under cold water until the water runs clear. Soak for 30 minutes, then drain.',
                        'In a large pot, bring 4 cups of water to a boil. Add cloves, cinnamon, cardamom, bay leaf, and salt.',
                        'Add the soaked rice and cook until it is 70-80% done (the grains should still have a bite).',
                        'Drain the rice and set aside.',
                        'COOK THE PRAWNS :',
                        'Heat oil in a pan over medium heat.',
                        'Add the marinated prawns and cook until they turn pink and are just cooked through. Do not overcook.',
                        'Remove from heat and set aside.',
                        'PREPATE THE BRIYANI BASE :',
                        'In the same pan, add ghee. Fry the sliced onions until they turn golden brown and crispy. Remove half for garnishing.',
                        'To the remaining onions in the pan, add green chilies and chopped tomatoes. Cook until the tomatoes soften.',
                        'Add yogurt, red chili powder, garam masala, biryani masala, and salt. Mix well and cook until the oil starts to separate from the masala.',
                        'Stir in the chopped mint and coriander leaves.',
                        'LAYER THE BRIYANI',
                        'In a heavy-bottomed pot or a biryani handi, spread half of the cooked rice.',
                        'Layer the cooked prawns over the rice, followed by the prepared masala.',
                        'Add the remaining rice on top.',
                        'Drizzle the saffron-infused milk over the rice and sprinkle the reserved fried onions.',
                        'DUM COOKING :',
                        'Cover the pot with a tight-fitting lid or seal it with dough to trap the steam.',
                        'Place the pot on a low flame or in a preheated oven at 180°C (350°F) for 20-25 minutes to allow the flavors to meld.',
                        'SERVE :',
                        'Garnish with fried onions and serve hot with raita (yogurt sauce) or a fresh salad.',

       ]         
    },
    'shrimp-briyani' : {
      title : 'SHRIMP BRIYANI',
      ingredients : ['FOR MARINATING THE SHRIMP',
                    '500g shrimp, peeled and deveined',
                    '1 tsp turmeric powder',
                    '1 tsp red chili powder',
                    '1 tsp cumin powder',
                    '1 tsp coriander powder',
                    '1 tbsp ginger-garlic paste',
                    '1 tbsp lime juice',
                    'Salt to taste',
                    'FOR RICE : ',
                    '2 cups basmati rice',
                      '4 cups water',
                      '2-3 cloves',
                      '1-inch cinnamon stick',
                      '2-3 green cardamom pods',
                      '1 bay leaf',
                      'Salt to taste',
                      'FOR BRIYANI',
                      '2 large onions, thinly sliced',
                      '2 tomatoes, chopped',
                      '2-3 green chilies, slit',
                      '1 cup coconut milk',
                      '1 tsp red chili powder',
                      '1 tsp garam masala',
                      '1 tsp shrimp masala or biryani masala (optional)',
                      '½ cup fresh mint leaves, chopped',
                      '½ cup fresh coriander leaves, chopped',
                      '2 tbsp ghee',
                      '3 tbsp vegetable oil',
                      'A few saffron strands soaked in 2 tbsp warm milk (or yellow food coloring)',
                      'Fried onions and lemon wedges (for garnish)',
                  
                  ],
        instructions : [ 'MARINATE THE SHRIMP : ',
                        'In a bowl, mix turmeric, red chili powder, cumin powder, coriander powder, ginger-garlic paste, lime juice, and salt.Add the shrimp and ensure they are well-coated with the marinade. Refrigerate for at least 30 minutes.',
                        'COOK THE RICE : ',
                        'Rinse the basmati rice until the water runs clear. Soak for 30 minutes, then drain. Bring 4 cups of water to a boil with cloves, cinnamon, cardamom, bay leaf, and salt.Add the rice and cook until 70-80% done. Drain and set aside.',
                        'COOK THE SHRIPM : ',
                        'Heat oil in a pan over medium heat.Add the marinated shrimp and sauté until they turn pink and are just cooked. Avoid overcooking.Remove from heat and set aside.',
                        'PREPARE THE BRIYANI BASE : ',
                        'In the same pan, add ghee. Fry the sliced onions until golden and crispy. Reserve half for garnishing. Add green chilies and chopped tomatoes to the remaining onions. Cook until tomatoes are soft.Stir in coconut milk, red chili powder, garam masala, and shrimp masala. Cook until the mixture thickens and the oil separates.Add chopped mint and coriander leaves.',
                        'LAYER THE BRIYANI : ',
                        'In a heavy-bottomed pot or biryani handi, layer half of the cooked rice.Add the cooked shrimp over the rice, followed by the masala.Top with the remaining rice.Pour the saffron milk over the rice and sprinkle the reserved fried onions.',
                        'DUM COOKING : ',
                        'Seal the pot with a tight lid or dough to trap steam. Cook on low heat or place in a preheated oven at 180°C (350°F) for 20-25 minutes.',
                        'SERVE : ',
                        'Garnish with fried onions and serve with lemon wedges and raita.'

        ]         

    },
    'beef-briyani' : {
      title : 'BEEF BRIYANI',
      ingredients : ['FOR MARINATING THE BEEF : ',
                    '500g beef, cut into bite-sized pieces (preferably bone-in for more flavor)',
                      '1 tsp turmeric powder',
                      '1 tsp red chili powder',
                      '1 tsp cumin powder',
                      '1 tsp coriander powder',
                      '1 tbsp ginger-garlic paste',
                      '1 tbsp yogurt',
                      '1 tbsp lemon juice',
                      'Salt to taste',
                      'FOR RICE',
                      '2 cups basmati rice',
                      '4 cups water',
                      '2-3 cloves',
                      '1-inch cinnamon stick',
                      '2-3 green cardamom pods',
                      '1 bay leaf',
                      'Salt to taste',
                      'FOR BRIYANI',
                      '2 large onions, thinly sliced',
                      '2 tomatoes, chopped',
                      '2-3 green chilies, slit',
                      '1 cup beef or vegetable broth',
                      '1 tsp red chili powder',
                      '1 tsp garam masala',
                      '1 tsp biryani masala',
                      '½ cup fresh mint leaves, chopped',
                      '½ cup fresh coriander leaves, chopped',
                      '2 tbsp ghee',
                      '3 tbsp vegetable oil',
                      'A few saffron strands soaked in 2 tbsp warm milk (or yellow food coloring)',
                      'Fried onions and boiled eggs (optional, for garnish)',
      ],
      instructions : ['MARINATE THE BEEF: ',
                       'In a large bowl, combine turmeric, red chili powder, cumin powder, coriander powder, ginger-garlic paste, yogurt, lemon juice, and salt.Add the beef pieces and mix well to coat. Marinate for at least 1 hour, preferably overnight in the refrigerator for deeper flavor.',
                      'COOK THE RICE : ',
                      'Rinse the basmati rice until the water runs clear. Soak for 30 minutes, then drain.In a large pot, bring 4 cups of water to a boil with cloves, cinnamon, cardamom, bay leaf, and salt.Add the soaked rice and cook until 70-80% done. Drain and set aside.',
                      'COOK THE BEEF : ',
                      'In a heavy-bottomed pot or pressure cooker, heat vegetable oil over medium heat.Add the marinated beef and sauté until browned on all sides.f using a pressure cooker, add beef broth, cover, and cook for about 20 minutes after the first whistle. If using a regular pot, add enough broth to cover the beef, cover, and simmer until the beef is tender (this may take 1-1.5 hours).Once cooked, the beef should be tender and the gravy thickened. Adjust salt as needed.',
                      'PREPARE THE BRIYANI BASE :' ,
                      'In another pan, heat ghee and fry the sliced onions until golden brown and crispy. Remove half for garnishing.To the remaining onions, add green chilies and chopped tomatoes. Cook until tomatoes soften.Add red chili powder, garam masala, and biryani masala. Stir well and cook for a few minutes.Incorporate the chopped mint and coriander leaves.',
                      'LAYER THE BRIYANI : ',
                      'In a heavy-bottomed pot or biryani handi, layer half of the cooked rice.Spread the cooked beef and its gravy over the rice.Add the onion-tomato masala layer.Top with the remaining rice.Drizzle saffron milk over the rice and sprinkle the reserved fried onions.',
                      'DUM COOKING :',
                      'Seal the pot with a tight-fitting lid or dough to trap the steam. Place the pot on a low flame or in a preheated oven at 180°C (350°F) for 25-30 minutes to allow flavors to meld',
                      'SERVE :',
                      'Garnish with fried onions and, if desired, boiled eggs. Serve hot with raita, salad, or pickles.'
      ]  
    },
    'Vegetable-briyani' : {
      title : 'VEGETABLE BRIYANI',
      ingredients : ['FOR RICE : ',
                     'Basmati rice : 2 cups',
                     'Water : 4 cups',
                     'Green cardamom pods : 2-3',
                     'Cloves : 4',
                     'Cinnamon stick : 1 -inch',
                     'Bay leaf : 1',
                     'Salt to taste',
                     'FOR VEGETABLE MASALA :',
                     'Oil or Ghee :  2 tbsps',
                     'Onion, thinly sliced : 2',
                     'Tomatoes, chopped : 2',
                     'Mixed vegetables(Carrot,beans,peas,potatoes),diced : 1 cup',
                     'Cauliflower florets : 1/2 cup',
                     'Green bell pepper, chopped : 1/2 cup',
                     'Green chillies : 2 slit',
                     'Giner-garlic paste : 1 tsp',
                     'Yougurt : 1/2 cup, whisked',
                     'Turmeric powder : 1 tsp',
                     'Red chili powder : 1 tsp',
                     'Garam masala powder : 1 tsp',
                     'Coriander powder : 1 tsp',
                     'Salt to taste',
                     'FOR BRIYANI LAYERING',
                     'Fried onions(birista) : 1/4 cup fried',
                     'Fresh coriander leaves, chopped : handful',
                     'Fresh mint leaves : handful',
                     'A few saffron strands soaked in 2 tsps of warm milk',
                     'Ghee : 2 tablespoons',             

      ],
      instructions : ['PREPARE THE RICE :',
                       'Rinse Basmati rice under cold water until the water runs clear.Soak the rice in water for 30 minutes. Drain.In a large pot, bring 4 cups of water to a boil. Add cardamom, cloves, cinnamon, bay leaf, and salt.Add the soaked rice and cook until 70% done. Drain and set aside.',
                       'COOK THE VEGETABLES :',
                       'Heat oil or ghee in a large pan over medium heat.Add sliced onions and sauté until golden brown.Add ginger-garlic paste and green chilies; sauté for another minute.Add chopped tomatoes and cook until they soften.Add diced mixed vegetables, cauliflower, and bell pepper. Sauté for 5-7 minutes.Stir in turmeric, red chili powder, coriander powder, and salt. Cook for 2 minutes.Add whisked yogurt and mix well. Cook until the vegetables are tender.Sprinkle garam masala and mix. Remove from heat.',
                       'LAYER THE BRIYANI :',
       
                       'In a large, heavy-bottomed pot, spread a layer of the cooked vegetable masala.Add a layer of partially cooked rice over the vegetables.Sprinkle fried onions, chopped coriander, and mint leaves.Drizzle saffron-infused milk and ghee over the rice.Repeat the layers if necessary, ending with a rice layer topped with fried onions and herbs.',
                       'DUM (STEAM COOKING) :',
                       'Cover the pot with a tight-fitting lid. You can seal the edges with dough to trap the steam.Cook on low heat for about 20-25 minutes to allow the flavors to meld.',
                       'SERVE :',
                       'Gently fluff the biryani before serving.',
                       'Serve hot with raita, salad, or your favorite chutney.',
      ]

    },
    'mushroom-briyani' : {
      title: 'MUSHROOM BRIYANI',
      ingredients : ['FOR RICE : ',
                    'Basmati rice : 2 cups',
                    'Water : 4 cups',
                    'Green cardamom pods : 2-3',
                    'cloves : 4',
                    'Cinnamon stick : 1- inch',
                    'Bay leaf : 1',
                    'Salt to taste',
                    'FOR MUSHROOM MASALA : ',
                    'Oil : 2 tablespoons',
                     'Onion, thinly sliced : 2',
                     'Tomatoes, chopped : 2',
                     'Mushrooms, cleaned and sliced : 500 grms',
                     'Giner-garlic paste : 1 tsp',
                     'Yougurt : 1/2 cup, whisked',
                     'Turmeric powder : 1 tsp',
                     'Red chili powder : 1 tsp',
                     'Garam masala powder : 1 tsp',
                     'Coriander powder : 1 tsp',
                     'Salt to taste',
                     'FOR BRIYANI LAYERING :',
                     'Fried onions(birista) : 1/4 cup fried',
                     'Fresh coriander leaves, chopped : handful',
                     'Fresh mint leaves : handful',
                     'A few saffron strands soaked in 2 tsps of warm milk',
                     'Ghee : 2 tablespoons',

      ],
      instructions : ['PREPARE THE RICE :',
                       'Rinse Basmati rice under cold water until the water runs clear.Soak the rice in water for 30 minutes. Drain.In a large pot, bring 4 cups of water to a boil. Add cardamom, cloves, cinnamon, bay leaf, and salt.Add the soaked rice and cook until 70% done. Drain and set aside.',
                      'COOK THE MUSHROOM MASALA :',
                      'Heat oil or ghee in a pan over medium heat.Add sliced onions and sauté until golden brown.Add ginger-garlic paste and green chilies; sauté for another minute.Add chopped tomatoes and cook until they soften.Add sliced mushrooms and cook until they release their moisture and reduce in size.Stir in turmeric, red chili powder, coriander powder, and salt. Cook for 2 minutes.Add whisked yogurt and mix well. Cook until the oil separates.Sprinkle garam masala and mix. Remove from heat.',
                      'LAYER THE BRIYANI :',
                      'In a large, heavy-bottomed pot, spread a layer of the cooked mushroom masala.Add a layer of partially cooked rice over the mushrooms.Sprinkle fried onions, chopped coriander, and mint leaves.Drizzle saffron-infused milk and ghee over the rice.Repeat the layers if necessary, ending with a rice layer topped with fried onions and herbs.',
                      'DUM(STEAM COOKING) :',
                      'Cover the pot with a tight-fitting lid. Seal the edges with dough if desired.Cook on low heat for about 20-25 minutes.',
                      'SERVE :',
                      'Gently fluff the biryani before serving.Serve hot with raita or your favorite side dish.'
                      ]

    },

    'paneer-briyani' : {
      title : 'PANNER BRIYANI',
      ingredients : ['FOR RICE :',
                    'Basmati rice : 2 cups',
                    'Water : 4 cups',
                    'Green cardamom pods : 2-3',
                    'cloves : 4',
                    'Cinnamon stick : 1- inch',
                    'Bay leaf : 1',
                    'Salt to taste',
                    'FOR PANNER MASALA : ',
                    'Oil : 2 tablespoons',
                     'Onion, thinly sliced : 2',
                     'Tomatoes, chopped : 2',
                     'Paneer, cubed : 250 grms',
                     'Green peas(optional) : 1/2 cup',
                     'Giner-garlic paste : 1 tsp',
                     'Yougurt : 1/2 cup, whisked',
                     'Turmeric powder : 1 tsp',
                     'Red chili powder : 1 tsp',
                     'Garam masala powder : 1 tsp',
                     'Coriander powder : 1 tsp',
                     'Salt to taste',
                     'FOR BRIYANI LAYERING :',
                     'Fried onions(birista) : 1/4 cup fried',
                     'Fresh coriander leaves, chopped : handful',
                     'Fresh mint leaves : handful',
                     'A few saffron strands soaked in 2 tsps of warm milk',
                     'Ghee : 2 tablespoons',
                    ],
         instructions : ['PREPARE THE RICE :',
                       'Rinse Basmati rice under cold water until the water runs clear. Soak the rice in water for 30 minutes. Drain. In a large pot, bring 4 cups of water to a boil. Add cardamom, cloves, cinnamon, bay leaf, and salt.Add the soaked rice and cook until 70% done. Drain and set aside.',
                      'PREPARE THE PANEER :',
                      'Optionally, lightly fry the paneer cubes until golden and set aside. This adds a nice texture but can be skipped for a softer paneer.',
                      'COOK THE PANNER MASALA :',
                      'Heat oil or ghee in a pan over medium heat.Add sliced onions and sauté until golden brown. Add ginger-garlic paste and green chilies; sauté for another minute.Add chopped tomatoes and cook until they soften.Stir in turmeric, red chili powder, coriander powder, and salt. Cook for 2 minutes.Add whisked yogurt and mix well. Cook until the oil separates.Add paneer cubes and green peas(if using).Gently mix to coat paneer with the masala.Sprinkle garam masala and mix. Remove from heat.',
                      'LAYER THE BRIYANI :',
                      'In a large, heavy-bottomed pot, spread a layer of the cooked mushroom masala. Add a layer of partially cooked rice over the paneer.Sprinkle fried onions, chopped coriander, and mint leaves.Drizzle saffron-infused milk and ghee over the rice.Repeat the layers if necessary, ending with a rice layer topped with fried onions and herbs.',
                      'DUM(STEAM COOKING) :',
                      'Cover the pot with a tight-fitting lid. Seal the edges with dough if desired.Cook on low heat for about 20-25 minutes.',
                      'SERVE :',
                      'Gently fluff the biryani before serving. Serve hot with raita or your favorite side dish.'
                    ]           


    },
    'palak-briyani' : {
      title : 'PALAK BRIYANI',
      ingredients : ['FOR RICE :',
                    'Basmati rice : 2 cups',
                    'Water : 4 cups',
                    'Green cardamom pods : 2-3',
                    'cloves : 4',
                    'Cinnamon stick : 1- inch',
                    'Bay leaf : 1',
                    'Salt to taste',

                     'FOR PALAK MASALA :',
                     'Oil : 2 tablespoons',
                     'Onion, thinly sliced : 2',
                     'Tomatoes, chopped : 2',
                     'Paneer, cubed : 250 grms',
                
                     'Giner-garlic paste : 1 tsp',
                     'Turmeric powder : 1 tsp',
                     'Red chili powder : 1 tsp',
                     'Garam masala powder : 1 tsp',
                     'Coriander powder : 1 tsp',
                     'Salt to taste',

                     'FOR BRIYANI LAYERING :',
                     'Fried onions(birista) : 1/4 cup fried',
                     'Fresh coriander leaves, chopped : handful',
                     'Fresh mint leaves : handful',
                     'A few saffron strands soaked in 2 tsps of warm milk',
                     'Ghee : 2 tablespoons',
                  ],

      instructions :['PREPARE THE RICE :',
                       'Rinse Basmati rice under cold water until the water runs clear. Soak the rice in water for 30 minutes. Drain.' ,
                       'In a large pot, bring 4 cups of water to a boil. Add cardamom, cloves, cinnamon, bay leaf, and salt.',
                       'Add the soaked rice and cook until 70% done. Drain and set aside.',
                       'PREPATE THE SPINACH (PALAK) MASALA :',
                       'Blanch the spinach leaves by boiling them in water for 2 minutes. Drain and blend into a smooth puree.',
                       'Heat oil or ghee in a pan over medium heat.',
                       'Add sliced onions and sauté until golden brown.',
                       'Add ginger-garlic paste and green chilies; sauté for another minute.',
                       'Add chopped tomatoes and cook until they soften.',
                       'Stir in turmeric, red chili powder, cumin powder, and salt. Cook for 2 minutes.',
                       'Add the spinach puree and mix well.',
                       'Sprinkle garam masala and mix. Remove from heat.',
                        'LAYER THE BRIYANI :',
                         'In a large, heavy-bottomed pot, spread a layer of the palak masala.',
                         'Add a layer of partially cooked rice over the spinach.',
                         'Sprinkle fried onions, chopped coriander, and mint leaves.',
                         'Drizzle saffron-infused milk(IF USING) and ghee over the rice.',
                         'Repeat the layers if necessary, ending with a rice layer topped with fried onions and herbs.',
                         'DUM (STEAM COOKING) :',
                         'Cover the pot with a tight-fitting lid. Seal the edges with dough if desired.',
                         'Cook on low heat for about 20-25 minutes.',
                         'SERVE :',
                         'Gently fluff the biryani before serving.',

                      ]            
    },
    'tomato-briyani' : {
      title : 'TOMATO BRIYANI',
      ingredients : ['FOR RICE :',
                    'Basmati rice : 2 cups',
                    'Water : 4 cups',
                    'Green cardamom pods : 2-3',
                    'cloves : 4',
                    'Cinnamon stick : 1- inch',
                    'Bay leaf : 1',
                    'Salt to taste',
                     
                    'FOR TOMATO MASALA :',
                     'Oil : 2 tablespoons',
                     'Onion, thinly sliced : 2',
                     'Tomatoes ripe : 4-5 pureed',
                      'Yogurt : 1/2 cup, whisked',
                     'Giner-garlic paste : 1 tsp',
                     'Turmeric powder : 1 tsp',
                     'Red chili powder : 1 tsp',
                     'Garam masala powder : 1 tsp',
                     'Coriander powder : 1 tsp',
                     'Salt to taste',

                     'FOR BRIYANI LAYERING :',
                     'Fried onions(birista) : 1/4 cup fried',
                     'Fresh coriander leaves, chopped : handful',
                     'Fresh mint leaves : handful',
                     'A few saffron strands soaked in 2 tsps of warm milk',
                     'Ghee : 2 tablespoons',
                  ],
      instructions : ['PREPARE THE RICE :',
                       'Rinse Basmati rice under cold water until the water runs clear. Soak the rice in water for 30 minutes. Drain.' ,
                       'In a large pot, bring 4 cups of water to a boil. Add cardamom, cloves, cinnamon, bay leaf, and salt.',
                       'Add the soaked rice and cook until 70% done. Drain and set aside.',
                       'PREPARE THE TOMATO MASALA :',
                       'Heat oil or ghee in a pan over medium heat.',
                       'Add sliced onions and sauté until golden brown.',
                       'Add ginger-garlic paste and green chilies; sauté for another minute.',
                       'Add tomato puree and cook until the oil starts to separate.',
                       'Stir in turmeric, red chili powder, cumin powder, coriander powder, and salt. Cook for 5-7 minutes.',
                       'Add whisked yogurt and mix well. Cook until the masala is well blended and the oil separates.',
                       'Sprinkle garam masala and mix. Remove from heat.',
                       'LAYER THE BRIYANI :',
                       'In a large, heavy-bottomed pot, spread a layer of the tomato masala.',
                       'Add a layer of partially cooked rice over the masala.',
                       'Sprinkle fried onions, chopped coriander, and mint leaves.',
                       'Drizzle saffron-infused milk and ghee over the rice.',
                       'Repeat the layers if necessary, ending with a rice layer topped with fried onions and herbs.',
                       'DUM (STEAM COOKING) :',
                       'Cover the pot with a tight-fitting lid. Seal the edges with dough if desired.',
                       'Cook on low heat for about 20-25 minutes.',
                       'SERVE :',
                       'Gently fluff the biryani before serving.',
                       'Serve hot with raita, salad, or chutney.'

                      
                      
                      ]            
    }
  
  }
//Add event listener to the left sidebar links

briyaniList.addEventListener('click', (e) => {
  recipeContent.style.color ='hwb(120 28% 71%)';
  recipeContent.style.fontSize = '18px';
  recipeContent.style.fontFamily =' Arial, Helvetica, sans-serif;'
  recipeContent.style.width = '250px';
  recipeContent.style.textAlign='center';
  
  
  e.preventDefault();
  if(e.target.tagName === 'A') {
    const recipeId = e.target.getAttribute('data-recipe');
    displayRecipe(recipes[recipeId]);
  
  }
});
//Function to display the selected recipe 
function displayRecipe(recipe) {
  if(!recipe) {
    recipeContent.innerHTML ="<h1>Recipe not found.</h1>";
    return;
  }
  const html = `
  <h1>${recipe.title}</h1><br> 
  <h2>Ingredients: </h2><br>
  
  ${recipe.ingredients.map((ingredient) =>
    `<li>${ingredient}</li>`).join('')}
    
    <br>
    <h2>Instructions:</h2><br>
    
    ${recipe.instructions.map((instruction) =>
    `<li>${instruction}</li>`).join('')}

    

    `;
   recipeContent.innerHTML = html;
  
}

